---
php_packages: [ "php-pear", "php-curl", "php-dev", "php-gd", "php-mbstring", "php-zip", "php-fpm", "php-mysql", "php-xml", "php-imagick", "php-tidy", "php-xmlrpc", "php-intl"]
php_file_uploads: "On"
php_upload_max_filesize: "64M"
php_max_file_uploads: "20"
php_post_max_size: "32M"