---
- name: Install MariaDB & mysql-python prereq
  apt: name={{ item }} update_cache=yes state=latest
  loop: [ 'mariadb-server', 'python3-pymysql' ]
  notify: Restart MariaDB

# MariaDB Configuration
- name: Sets the root password
  mysql_user:
    login_host: 'localhost'
    login_user: 'root'
    login_password: '{{ mysql_root_password}}'

    name: root
    host: 'localhost'
    password: "{{ mysql_root_password}}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
 # ignore_errors: "{{ ansible_check_mode }}" # ja dodalem
  no_log: false # ja zminilem

- name: Removes all anonymous user accounts
  mysql_user:
    login_host: 'localhost'
    login_user: 'root'
    login_password: '{{ mysql_root_password}}'

    name: ''
    host_all: yes
    state: absent
    login_unix_socket: /var/run/mysqld/mysqld.sock
  notify: Restart MariaDB
  no_log: false #  ja zminilem na false

- name: Removes the MySQL test database
  mysql_db:
    login_host: 'localhost'
    login_user: 'root'
    login_password: '{{ mysql_root_password}}'

    name: test
    state: absent
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Creates App Database
  mysql_db:
    login_host: 'localhost'
    login_user: 'root'
    login_password: '{{ mysql_root_password}}'

    name: "{{ mysql_app_db }}"
    state: present
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Create App MySQL user and grants access to App DB
  mysql_user:
    login_host: 'localhost'
    login_user: 'root'
    login_password: '{{ mysql_root_password}}'

    name: "{{ mysql_app_user }}"
    password: "{{ mysql_app_pass }}"
    priv: "{{ mysql_app_db }}.*:ALL"
    state: present
    login_unix_socket: /var/run/mysqld/mysqld.sock
  notify: Restart MariaDB
  no_log: true