---
copy_local_key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"
sys_packages: [ 'curl', 'vim', 'git','mc']

## SYS_PACKAGES 
# is the list of system packages to be installed on the server.
# You can add or remove packages as needed.
# sys_packages: [ 'curl', 'vim', 'git', 'ufw', 'acl', 'mc' ]